# Generated by Django 2.2.1 on 2019-05-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_searchquery'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'shop')},
        ),
    ]
